### ISSUE TITLE
Odd possibility of connecting thick and lean pipes together

### ISSUE THREAD

**Issue by patrykwilk90** [raiguard/FluidMustFlow#23] opened 2023-11-18 13:14 UTC
### Description

Take a look at the attached gif showing the issue.

### Reproduction

https://drive.google.com/file/d/1aZl4uo-ewQu4hMuFcI_7_pqzqPEchZVu/view

**Comment by raiguard** [comment] 2023-11-19 08:01
This is a known issue and cannot be fixed at the moment. It will be fixed in Factorio 2.0.

Duplicate of #19

**Closed by raiguard** 2023-11-19 08:01 UTC
